from __future__ import annotations

from typing import Any, List, Optional, Protocol, Sequence

from pyspark.sql import DataFrame, SparkSession

from fabricks.cdc import CDCIntentContext
from fabricks.core.jobs.config import JobConfig
from fabricks.metastore.table import SchemaDiff, Table
from fabricks.models import (
    AllowedChangeDataCaptures,
    AllowedModes,
    TOptions,
)


class CheckableJob(Protocol):
    """Narrow interface required by JobChecker."""

    @property
    def config(self) -> JobConfig: ...

    @property
    def mode(self) -> AllowedModes: ...

    @property
    def table(self) -> Table: ...

    def __str__(self) -> str: ...


class InvocableJob(Protocol):
    """Narrow interface required by JobInvoker."""

    @property
    def config(self) -> JobConfig: ...

    @property
    def options(self) -> TOptions: ...

    def __str__(self) -> str: ...


class StorableCDC(Protocol):
    """Narrow CDC interface required by JobDBA — the 8 methods it actually calls."""

    def drop(self) -> None: ...

    def create_table(self, src: Any, **kwargs) -> None: ...

    def create_or_replace_view(self, src: Any, schema_evolution: bool = True, **kwargs) -> None: ...

    def optimize_table(self) -> None: ...

    def get_schema_differences(self, src: Any, **kwargs) -> Optional[Sequence[SchemaDiff]]: ...

    def get_differences_with_deltatable(self, src: Any, **kwargs) -> Any: ...

    def update_schema(self, src: Any, **kwargs) -> None: ...

    def overwrite_schema(self, src: Any, **kwargs) -> None: ...


class StorableJob(Protocol):
    """Narrow interface required by JobDBA."""

    @property
    def config(self) -> JobConfig: ...

    @property
    def mode(self) -> AllowedModes: ...

    @property
    def stream(self) -> bool: ...

    @property
    def persist(self) -> bool: ...

    @property
    def virtual(self) -> bool: ...

    @property
    def options(self) -> TOptions: ...

    @property
    def table(self) -> Table: ...

    @property
    def cdc(self) -> StorableCDC: ...

    def get_cdc_context(self, df: DataFrame, reload: Optional[bool] = False) -> CDCIntentContext: ...

    def base_transform(self, df: DataFrame) -> DataFrame: ...

    def create_or_replace_view(self) -> None: ...

    def __str__(self) -> str: ...


class RunnableJob(Protocol):
    """Narrow interface required by JobRunner."""

    @property
    def config(self) -> JobConfig: ...

    @property
    def schema_drift(self) -> bool: ...

    @property
    def persist(self) -> bool: ...

    @property
    def stream(self) -> bool: ...

    @property
    def virtual(self) -> bool: ...

    @property
    def mode(self) -> AllowedModes: ...

    @property
    def table(self) -> Table: ...

    @property
    def options(self) -> TOptions: ...

    def get_data(self, stream: bool = False, transform: Optional[bool] = None, **kwargs) -> Optional[DataFrame]: ...

    def base_transform(self, df: DataFrame) -> DataFrame: ...

    def for_each_batch(self, df: DataFrame, batch: Optional[int] = None, **kwargs) -> None: ...

    def create_or_replace_view(self) -> None: ...

    def get_schema_differences(self, df: Optional[DataFrame] = None) -> Optional[Sequence[SchemaDiff]]: ...

    def update_schema(self, df: Optional[DataFrame] = None, widen_types: Optional[bool] = False) -> None: ...

    def restore(self, last_version: Optional[str] = None, last_batch: Optional[str] = None) -> None: ...

    def maintain(self, vacuum: bool = True, optimize: bool = True, compute_statistics: bool = True) -> None: ...

    def __str__(self) -> str: ...
