from pyspark.sql.types import StringType, StructField, StructType
import pytest

from fabricks.metastore.table import Table

# Real table-feature behavior needing actual Delta table state to verify, one
# function per feature -- mirrors tests/spark/databricks/runtime_min/gold/gold/
# feature/'s own split (feature_mask/feature_cluster_by), but for whichever
# features are genuine open-source Delta Lake protocol rather than
# Databricks/Unity-Catalog-only. Column masking and liquid clustering stay in
# runtime_min's feature/ topic instead -- see its README for why those two
# can't move here.


@pytest.mark.order(20)
def test_feature_identity(local_spark):
    """Table.create(identity=True) emits real `generated by default as
    identity` DDL (fabricks/metastore/table.py's _create(), identity branch)
    against a real Delta table -- not just that the identityColumns
    protocol feature exists (identity_enabled only reads that back after
    the fact). Confirms delta-spark>=4.4.0 actually executes this DDL under
    OSS Spark: Delta 4.4.0 added direct `GENERATED ... AS IDENTITY` SQL
    support in CREATE TABLE, which the delta-spark version this repo was
    previously pinned to (4.2.0) did not have.
    """
    table = Table("gold", "identity", "test", spark=local_spark)
    schema = StructType([StructField("name", StringType(), True)])
    table.create(schema=schema, identity=True)

    local_spark.sql(f"insert into {table.qualified_name} (name) values ('a'), ('b')")
    rows = local_spark.table(table.qualified_name).orderBy("__identity").collect()

    assert [row["__identity"] for row in rows] == [1, 2]
    assert table.identity_enabled
