from pyspark.sql.types import StringType, StructField, StructType
import pytest

from fabricks.metastore.table import Table

# Column masking and liquid clustering are Databricks/Unity-Catalog-only, so they stay in
# tests/spark/databricks/runtime.


@pytest.mark.order(20)
def test_feature_identity(local_spark):
    """Table.create(identity=True) emits `generated by default as identity` DDL; OSS Spark needs delta-spark>=4.4.0."""
    table = Table("gold", "identity", "test", spark=local_spark)
    schema = StructType([StructField("name", StringType(), True)])
    table.create(schema=schema, identity=True)

    local_spark.sql(f"insert into {table.qualified_name} (name) values ('a'), ('b')")
    rows = local_spark.table(table.qualified_name).orderBy("__identity").collect()

    assert [row["__identity"] for row in rows] == [1, 2]
    assert table.identity_enabled


@pytest.mark.order(21)
def test_feature_column_comment(local_spark):
    """Table.create(comments={...}) emits a `comment '...'` column clause; plain SQL, no Unity Catalog needed."""
    table = Table("gold", "comment", "test", spark=local_spark)
    schema = StructType([StructField("name", StringType(), True)])
    table.create(schema=schema, comments={"name": "the name of a person"})

    column = local_spark.sql(f"describe table {table.qualified_name}").where("col_name = 'name'").collect()[0]

    assert column["comment"] == "the name of a person"
