from pyspark.sql.types import StringType, StructField, StructType
import pytest

from fabricks.metastore.table import Table


@pytest.mark.order(20)
def test_identity_column(local_spark):
    """Table.create(identity=True) emits real `generated by default as
    identity` DDL (fabricks/metastore/table.py's _create(), identity branch)
    against a real Delta table -- not just that the identityColumns
    protocol feature exists (identity_enabled only reads that back after
    the fact). Confirms delta-spark>=4.4.0 actually executes this DDL under
    OSS Spark: Delta 4.4.0 added direct `GENERATED ... AS IDENTITY` SQL
    support in CREATE TABLE, which the delta-spark version this repo was
    previously pinned to (4.2.0) did not have.
    """
    table = Table("gold", "identity", "test", spark=local_spark)
    schema = StructType([StructField("name", StringType(), True)])
    table.create(schema=schema, identity=True)

    local_spark.sql(f"insert into {table.qualified_name} (name) values ('a'), ('b')")
    rows = local_spark.table(table.qualified_name).orderBy("__identity").collect()

    assert [row["__identity"] for row in rows] == [1, 2]
    assert table.identity_enabled
