from pyspark.sql.types import StringType, StructField, StructType
import pytest

from fabricks.metastore.table import Table

# Real table-feature behavior needing actual Delta table state to verify, one
# function per feature -- mirrors tests/spark/databricks/runtime/gold/gold/
# feature/'s own split (feature_mask/feature_cluster_by), but for whichever
# features are genuine open-source Delta Lake protocol rather than
# Databricks/Unity-Catalog-only. Column masking and liquid clustering stay in
# runtime's feature/ topic instead -- see its README for why those two
# can't move here.


@pytest.mark.order(20)
def test_feature_identity(local_spark):
    """Table.create(identity=True) emits real `generated by default as
    identity` DDL (fabricks/metastore/table.py's _create(), identity branch)
    against a real Delta table -- not just that the identityColumns
    protocol feature exists (identity_enabled only reads that back after
    the fact). Confirms delta-spark>=4.4.0 actually executes this DDL under
    OSS Spark: Delta 4.4.0 added direct `GENERATED ... AS IDENTITY` SQL
    support in CREATE TABLE, which the delta-spark version this repo was
    previously pinned to (4.2.0) did not have.
    """
    table = Table("gold", "identity", "test", spark=local_spark)
    schema = StructType([StructField("name", StringType(), True)])
    table.create(schema=schema, identity=True)

    local_spark.sql(f"insert into {table.qualified_name} (name) values ('a'), ('b')")
    rows = local_spark.table(table.qualified_name).orderBy("__identity").collect()

    assert [row["__identity"] for row in rows] == [1, 2]
    assert table.identity_enabled


@pytest.mark.order(21)
def test_feature_column_comment(local_spark):
    """Table.create(comments={...}) emits a real `comment '...'` column DDL
    clause (fabricks/metastore/table.py's _get_ddl_columns) -- plain ANSI
    SQL, no Unity Catalog needed, unlike masks/liquid clustering.
    """
    table = Table("gold", "comment", "test", spark=local_spark)
    schema = StructType([StructField("name", StringType(), True)])
    table.create(schema=schema, comments={"name": "the name of a person"})

    column = local_spark.sql(f"describe table {table.qualified_name}").where("col_name = 'name'").collect()[0]

    assert column["comment"] == "the name of a person"


# Column widening (Table.update_schema(widen_types=True) -> change_column()'s
# manual `alter table ... change column ... type ...`) was attempted here and
# dropped after 3 failed attempts: the schema diff is correctly detected
# ("changed column value (bigint -> double)" in DEFAULT_LOGGER output) but
# the ALTER silently has no effect even with delta.enableTypeWidening set both
# via CREATE TABLE's TBLPROPERTIES and via a follow-up ALTER TABLE ... SET
# TBLPROPERTIES -- change_column()'s bare `except Exception: pass` swallows
# whatever the real error is. Needs a real Delta-protocol investigation
# (minReaderVersion/minWriterVersion negotiation, not just the boolean
# property) before another attempt -- not a quick win.
