---
# yaml-language-server: $schema=../../../tests/integration/runtime/job-schema.json
- job:
    step: gold
    topic: demo
    item: hello_world
    tags: [example]
    options:
      mode: complete

