"""Fast checks for Table._create()'s table_options -> DDL mapping
(tblproperties, cluster by, identity, primary/foreign keys, masks,
comments), without a real Spark session or Delta table.

Table._create() (framework/fabricks/metastore/table.py) always executes the
DDL it builds via self.spark.sql(sql) - it never returns the string - so
these tests capture it off a mocked spark instead. The column-DDL half
(_get_ddl_columns) is NOT stubbed: pyspark's type system (StructType/
StructField) is pure Python and needs no running SparkSession to
construct (confirmed empirically), so a small dataclass stand-in carries a
real schema, letting masks/comments - which _get_ddl_columns applies per
column - be tested for real instead of bypassed.
"""

from dataclasses import dataclass, field
from unittest.mock import MagicMock

from pyspark.sql.types import IntegerType, StringType, StructField, StructType

from fabricks.metastore.table import Table
from fabricks.models import ForeignKey, PrimaryKey


@dataclass
class _FakeDF:
    columns: list[str]
    schema: StructType
    dtypes: list[tuple[str, str]] = field(default_factory=list)

    def __post_init__(self):
        if not self.dtypes:
            self.dtypes = [(f.name, f.dataType.simpleString()) for f in self.schema.fields]


def _fake_df(**columns_and_types) -> _FakeDF:
    """columns_and_types: name=DataType() pairs, e.g. dummy=StringType()."""
    schema = StructType([StructField(name, dtype) for name, dtype in columns_and_types.items()])
    return _FakeDF(columns=list(columns_and_types), schema=schema)


def _make_table(df: _FakeDF | None = None) -> tuple[Table, MagicMock, _FakeDF]:
    mock_spark = MagicMock(name="fake_spark")
    mock_spark.catalog.tableExists.return_value = False

    table = Table("gold", "fact", "option", spark=mock_spark)

    if df is None:
        df = _fake_df(dummy=StringType())

    return table, mock_spark, df


def _generated_sql(mock_spark: MagicMock) -> str:
    return mock_spark.sql.call_args[0][0]


def test_create_ddl_includes_tblproperties_from_table_options():
    table, mock_spark, df = _make_table()

    table._create(df=df, properties={"delta.columnMapping.mode": "name"})

    sql = _generated_sql(mock_spark)
    assert "TBLPROPERTIES" in sql
    assert "'delta.columnMapping.mode'='name'" in sql


def test_create_ddl_includes_cluster_by_from_liquid_clustering():
    table, mock_spark, df = _make_table()

    table._create(df=df, liquid_clustering=True, cluster_by=["monarch"])

    sql = _generated_sql(mock_spark)
    assert "CLUSTER BY (" in sql
    assert "`monarch`" in sql


def test_create_ddl_cluster_by_auto_when_no_columns_given():
    table, mock_spark, df = _make_table()

    table._create(df=df, liquid_clustering=True)

    assert "CLUSTER BY `auto`" in _generated_sql(mock_spark)


def test_create_ddl_includes_identity_column():
    table, mock_spark, df = _make_table()

    table._create(df=df, identity=True)

    sql = _generated_sql(mock_spark)
    assert "`__identity` BIGINT GENERATED BY DEFAULT AS IDENTITY" in sql


def test_create_ddl_omits_identity_column_by_default():
    table, mock_spark, df = _make_table()

    table._create(df=df)

    assert "__identity" not in _generated_sql(mock_spark)


def test_create_ddl_includes_primary_key_constraint():
    df = _fake_df(dummy=StringType(), id=IntegerType())
    table, mock_spark, df = _make_table(df)

    table._create(df=df, primary_key={"pk_dummy": PrimaryKey(keys=["id"])})

    assert "CONSTRAINT `pk_dummy` PRIMARY KEY (`id`)" in _generated_sql(mock_spark)


def test_create_ddl_includes_foreign_key_constraint():
    df = _fake_df(dummy=StringType(), less_dummy=StringType(), dummier=StringType())
    table, mock_spark, df = _make_table(df)

    table._create(
        df=df,
        foreign_keys={
            "fk_dummy": ForeignKey(keys=["dummy", "less_dummy", "dummier"], reference="gold.fact_primary_key")
        },
    )

    sql = _generated_sql(mock_spark)
    assert "CONSTRAINT `fk_dummy` FOREIGN KEY (`dummy`, `less_dummy`, `dummier`)" in sql
    assert "REFERENCES `gold`.`fact_primary_key`" in sql


def test_create_ddl_includes_column_masks_and_comments():
    df = _fake_df(dummy=StringType())
    table, mock_spark, df = _make_table(df)

    table._create(
        df=df,
        masks={"dummy": "mask_dummy"},
        comments={"dummy": "This is a dummy comment"},
    )

    # sqlglot's `fix()` normalization (uppercasing, etc. - see the other
    # tests in this file) silently fails on this particular DDL shape
    # (contextlib.suppress(Exception) in Table._create() swallows it),
    # leaving the raw, un-normalized SQL Table._create() itself builds -
    # confirmed empirically. Asserting on that raw shape, not the
    # normalized one.
    sql = _generated_sql(mock_spark)
    assert "comment 'This is a dummy comment'" in sql
    assert "mask mask_dummy" in sql


def test_create_ddl_omits_masks_and_comments_for_columns_not_listed():
    df = _fake_df(dummy=StringType(), untouched=StringType())
    table, mock_spark, df = _make_table(df)

    table._create(df=df, masks={"dummy": "mask_dummy"}, comments={"dummy": "commented"})

    sql = _generated_sql(mock_spark)
    assert "`untouched` string" in sql
    assert "untouched` string comment" not in sql
    assert "untouched` string mask" not in sql
    assert "mask mask_dummy" in sql


def test_create_ddl_defaults_column_mapping_when_special_chars_in_columns():
    df = _fake_df(**{"Näàme": StringType()})
    table, mock_spark, df = _make_table(df)

    table._create(df=df)

    sql = _generated_sql(mock_spark)
    assert "'delta.columnMapping.mode'='name'" in sql
    assert "'delta.minReaderVersion'='2'" in sql
