/databricks/python/bin/pip install azure-data-tables >=12.5.0,<13
/databricks/python/bin/pip install azure-identity >=1.10.0
/databricks/python/bin/pip install azure-storage-blob >=12.14.1
/databricks/python/bin/pip install azure-storage-queue >=12.10.0,<13
/databricks/python/bin/pip install databricks-cli>=0.18.0
/databricks/python/bin/pip install databricks-connect >=11.0.0
/databricks/python/bin/pip install databricks-sdk >=0.20.0
/databricks/python/bin/pip install deptry>=0.23.1
/databricks/python/bin/pip install ipython>=8.18.1
/databricks/python/bin/pip install jinja2 >=2.11.3
/databricks/python/bin/pip install mermaid-magic>=0.1.4
/databricks/python/bin/pip install pandas>=2.2.3
/databricks/python/bin/pip install py4j>=0.10.9.7
/databricks/python/bin/pip install pydantic>=1.10.21
/databricks/python/bin/pip install pydantic-settings>=2.11.0
/databricks/python/bin/pip install pyspark>=3.5.7
/databricks/python/bin/pip install python-dotenv >=1.0.1
/databricks/python/bin/pip install pyyaml >=6.0.0
/databricks/python/bin/pip install sparkdantic>=1.5.0
/databricks/python/bin/pip install sqlglot >=22.1.1
/databricks/python/bin/pip install tenacity>=9.1.2
/databricks/python/bin/pip install tomli>=2.2.1;python_version<"3.11"
/databricks/python/bin/pip install tqdm>=4.67.1