site_name: Fabricks
theme:
  name: readthedocs
  locale: en
nav:
  - Introduction: 'index.md'
  - Steps:
    - Steps: 'steps.md'
    - Bronze: 'steps/bronze.md'
    - Silver: 'steps/silver.md'
    - Gold: 'steps/gold.md'
    - Semantic: 'steps/semantic.md'
  - Examples:
    - Sample runtime: 'examples/runtime/index.md'
  - About:
    - License: license.md
    - Release Notes: release-notes.md
repo_url: https://github.com/fabricks-framework/fabricks
repo_name: fabricks-framework/fabricks
edit_uri: blob/main/framework/docs/
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
