site_name: Fabricks
theme:
  name: readthedocs
  locale: en
nav:
  - Introduction: 'index.md'
  - Steps:
    - Steps: 'steps.md'
    - Bronze: 'steps/bronze.md'
    - Silver: 'steps/silver.md'
    - Gold: 'steps/gold.md'
  - About:
    - License: license.md
    - Release Notes: release-notes.md
repo_url: https://github.com/fabricks-framework/fabricks
