---
site_name: Fabricks
theme:
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  name: material
  locale: en
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
nav:
  - Introduction:
      - Intro: index.md
      - Overview: introduction/overview.md
      - Layers: introduction/layers.md
  - Steps:
      - Bronze: steps/bronze.md
      - Silver: steps/silver.md
      - Gold: steps/gold.md
  - Reference:
      - Change Data Capture (CDC): reference/cdc.md
      - Checks & Data Quality: reference/checks-data-quality.md
      - Table Options: reference/table-options.md
      - Extenders, UDFs & Parsers: reference/extenders-udfs-parsers.md
  - Helpers:
      - Initialize: helpers/init.md
      - Runtime: helpers/runtime.md
      - Job: helpers/job.md
      - Step: helpers/step.md
      - Schedule: helpers/schedule.md
repo_url: https://github.com/fabricks-framework/fabricks
repo_name: fabricks-framework/fabricks
edit_uri: blob/main/framework/docs/
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
