site_name: Fabricks
theme:
  features:
    - content.code.copy
    - content.code.annotate
  name: material  
  locale: en
nav:
  - Introduction: 'index.md'
  - Steps:
    - Bronze: 'steps/bronze.md'
    - Silver: 'steps/silver.md'
    - Gold: 'steps/gold.md'
  - Runtime: 'runtime.md'
  - Reference:
    - Change Data Capture (CDC): 'reference/cdc.md'
    - Checks & Data Quality: 'reference/checks-data-quality.md'
    - Table Options: 'reference/table-options.md'
    - Extenders, UDFs & Views: 'reference/extenders-udfs-views.md'
  - Helpers:
    - Initialize: 'helpers/init.md'
    - Job: 'helpers/job.md'
    - Step: 'helpers/step.md'
  - About:
    - License: license.md
    - Release Notes: release-notes.md
repo_url: https://github.com/fabricks-framework/fabricks
repo_name: fabricks-framework/fabricks
edit_uri: blob/main/framework/docs/
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences