---
# yaml-language-server: $schema=../../tests/integration/runtime/job-schema.json
- job:
    step: semantic
    topic: demo
    item: table
    tags: [example]
    options:
      mode: complete
      table: gold.demo_hello_world

