---
# yaml-language-server: $schema=../../tests/integration/runtime/job-schema.json
- job:
    step: silver
    topic: demo
    item: scd1
    tags: [example]
    options:
      mode: update
      change_data_capture: scd1
      parents: [bronze.demo_source]

